# Generated by Django 5.1.1 on 2024-10-08 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_rename_description_failureinfo_failuredescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failureinfo',
            name='faildate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
