# Generated by Django 5.1.1 on 2024-10-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_alter_cells_name_id_alter_failure_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='station_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_Name', models.CharField(max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
