# Generated by Django 5.1.1 on 2024-10-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_failureinfo_faildate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failureinfo',
            name='faildate',
        ),
    ]
