# Generated by Django 5.1.1 on 2024-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure_mode',
            name='test_Cells',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
