# Generated by Django 5.1.1 on 2024-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_failure_mode_test_cells'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_Name', models.CharField(max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
