# Generated by Django 5.1.1 on 2024-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_info',
            name='test_Cells',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
