# Generated by Django 5.1.1 on 2024-10-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_remove_failureinfo_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failureinfo',
            old_name='faildate',
            new_name='fail_date',
        ),
        migrations.RenameField(
            model_name='failureinfo',
            old_name='failureDescription',
            new_name='failure_Description',
        ),
        migrations.RenameField(
            model_name='failureinfo',
            old_name='testStation',
            new_name='failure_Station',
        ),
        migrations.AddField(
            model_name='failureinfo',
            name='test_cells',
            field=models.CharField(choices=[('PCA Burn IN', 'PCA Burn IN'), ('Calibration', 'Calibration'), ('Final Test', 'Final Test'), ('Temperature Test', 'Temperature Test'), ('Manual Test', 'Manual Test'), ('LCD Check', 'LCD Check'), ('Laser Alignment', 'Laser Alignment'), ('Manual Test', 'Manual Test')], max_length=20, null=True),
        ),
    ]
