# Generated by Django 5.1.1 on 2024-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_alter_sku_info_test_cells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_Cells', models.CharField(max_length=100, null=True)),
                ('product_Model', models.CharField(max_length=100, null=True)),
                ('FG_PartNo', models.CharField(max_length=100, null=True)),
                ('FG_Model', models.CharField(max_length=100, null=True)),
                ('PCA_SN_Number', models.CharField(max_length=100, null=True)),
                ('test_Station', models.CharField(max_length=100, null=True)),
                ('failure_mode', models.CharField(max_length=100, null=True)),
                ('failure_action', models.CharField(max_length=100, null=True)),
                ('failure_status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
