# Generated by Django 5.1.1 on 2024-10-14 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_failure_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure_info',
            name='failure_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
