# Generated by Django 5.1.1 on 2024-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_rename_faildate_failureinfo_fail_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failureinfo',
            old_name='fail_date',
            new_name='failure_date',
        ),
        migrations.AlterField(
            model_name='failureinfo',
            name='test_cells',
            field=models.CharField(choices=[('CRICKET', 'CRICKET'), ('FANJI', 'FANJI'), ('BASS', 'BASS'), ('CARP', 'CARP'), ('BEIDOU', 'BEIDOU'), ('72X', '72X'), ('HPUMP HTP', 'HPUMP HTP'), ('5X', '5X'), ('TIC300', 'TIC300'), ('LEPTON', 'LEPTON'), ('ZULU', 'ZULU'), ('SHAKA', 'SHAKA'), ('PRO3000 PROBE', 'PRO3000 PROBE'), ('PRO3000 TONER', 'PRO3000 TONER'), ('INTELLITONE PROBE', 'INTELLITONE PROBE'), ('INTELLITONE TONER', 'INTELLITONE TONER'), ('MS2', 'MS2'), ('MS-POE', 'MS-POE'), ('WIREMAP', 'WIREMAP')], max_length=20, null=True),
        ),
    ]
