# Generated by Django 5.1.1 on 2024-10-09 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_rename_fail_date_failureinfo_failure_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getDebugData',
            new_name='Failure_Mode',
        ),
        migrations.RenameModel(
            old_name='failureInfo',
            new_name='SKU_Info',
        ),
        migrations.RenameField(
            model_name='sku_info',
            old_name='test_cells',
            new_name='test_Cells',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
