# Generated by Django 5.1.1 on 2024-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_failure_info_failure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_PCA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PCA_SN_Number', models.CharField(max_length=100, null=True)),
                ('product_Model', models.CharField(max_length=100, null=True)),
                ('FG_PartNo', models.CharField(max_length=100, null=True)),
                ('FG_Model', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
