# Generated by Django 5.1.1 on 2024-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_search_pca'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure_info',
            name='PCA_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='failure_info',
            name='reject_bin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
