# Generated by Django 5.1.1 on 2024-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_rename_getdebugdata_failure_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku_info',
            old_name='model',
            new_name='FG_Model',
        ),
        migrations.RemoveField(
            model_name='sku_info',
            name='failure_Description',
        ),
        migrations.RemoveField(
            model_name='sku_info',
            name='failure_Station',
        ),
        migrations.RemoveField(
            model_name='sku_info',
            name='failure_date',
        ),
        migrations.AddField(
            model_name='sku_info',
            name='FG_PartNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sku_info',
            name='product_Model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sku_info',
            name='product_Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=20, null=True),
        ),
    ]
