# Generated by Django 5.1.1 on 2024-10-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_rename_model_sku_info_fg_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cells_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_Name', models.CharField(max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
