# Generated by Django 5.1.1 on 2024-10-17 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_failure_info_pca_serial_failure_info_reject_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure_info',
            old_name='FG_Model',
            new_name='root_cause',
        ),
        migrations.RemoveField(
            model_name='failure_info',
            name='FG_PartNo',
        ),
        migrations.AddField(
            model_name='failure_info',
            name='Findings',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='failure_info',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
