# Generated by Django 5.1.1 on 2024-10-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0011_cells_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_info',
            name='test_Cells',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.cells_name'),
        ),
    ]
