# Generated by Django 5.1.1 on 2024-10-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0013_failure_info_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure_info',
            name='completion_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='failure_info',
            name='failure_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
