# Generated by Django 5.1.1 on 2024-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0014_alter_failure_info_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure_info',
            name='failure_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
