# Generated by Django 5.1.1 on 2024-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0015_remove_failure_mode_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure_mode',
            name='failure_Mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
