# Generated by Django 5.1.2 on 2024-11-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0016_alter_failure_mode_test_station_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='engTech',
            new_name='TroubleShooter',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'TS'), ('3', 'OPERATOR')], default=1, max_length=10),
        ),
    ]
