# Generated by Django 5.1.2 on 2024-11-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0017_rename_engtech_troubleshooter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_Taken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_Taken', models.CharField(max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
