# Generated by Django 5.1.1 on 2024-10-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0017_failure_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure_data',
            old_name='date',
            new_name='date_Registered',
        ),
        migrations.AlterField(
            model_name='failure_data',
            name='failure_Mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.failure_mode'),
        ),
    ]
