# Generated by Django 5.1.2 on 2024-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0018_action_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='root_Cause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_Cause', models.CharField(max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
