# Generated by Django 5.1.1 on 2024-10-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0019_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
