# Generated by Django 5.1.2 on 2024-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0020_remove_action_taken_date_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure_info',
            name='failure_Category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
