# Generated by Django 5.1.2 on 2024-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0021_failure_info_failure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure_info',
            name='escalation_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
