# Generated by Django 5.1.2 on 2024-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0023_remove_sku_info_fg_partno_sku_info_pca_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku_info',
            name='PCA_price',
        ),
        migrations.RemoveField(
            model_name='sku_info',
            name='PCA_price_currency',
        ),
        migrations.AddField(
            model_name='sku_info',
            name='FG_PartNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
