# Generated by Django 5.1.2 on 2024-12-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0024_remove_sku_info_pca_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku_info',
            name='FG_PartNo',
        ),
        migrations.AddField(
            model_name='sku_info',
            name='PCA_Price_USD',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
