# Generated by Django 5.1.2 on 2024-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0025_remove_sku_info_fg_partno_sku_info_pca_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure_info',
            name='reject_bin',
        ),
        migrations.AddField(
            model_name='failure_info',
            name='PCA_Price_USD',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
